# Generated by Django 3.0.7 on 2020-06-10 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descritpion', models.TextField(blank=True)),
                ('github', models.URLField()),
                ('email', models.CharField(max_length=100)),
                ('top_creator', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
